spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec201907b
    username: postgres
    password: postgres

  jmx:       
    enabled: false
    
server:
 servlet:
  context-path: /ec-201907b-saito