spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec201907b
    username: postgres
    password: postgres


  mail:
    default-encoding: UTF-8
    host: localhost #ローカルホストのSMTP4DEVに変更
    port: 25 #SMTP4DEVの初期値番号25に変更
    password: abc #環境変数のメールパスワードを取得
    username: test@test.co.jp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    

  jmx:       
    enabled: false
    
    
server:
 servlet:
  context-path: /ec-201907b-saito
  
  

    #host: smtp.gmail.com
    #port: 587
    #username: ${GoogleMail:bar} #環境変数のメールアドレスを取得
    #password: ${GooglePass:bar} #環境変数のメールパスワードを取得
